### PR TITLE
Add BSC networks

### PR DESCRIPTION
**Pull request by leetdev**
Add network configuration for BSC Mainnet and Testnet.

### CODE REVIEW

**Review by foufrix — APPROVED** [review]

**Comment by leetdev** [comment]
@posix4e, I've rebased and fixed conflicts in both repositories.

**Comment by posix4e** [comment]
@m00n620 kets review it together

**Review by m00n620 — APPROVED** [review]
LGTM

**Review by posix4e — APPROVED** [review]

**Comment by ivhus** [comment]
this is a PR from external forked repo, in order for deployment to work needed to be internal PR

**Comment by ivhus** [comment]
also, it should be a PR to `develop` branch rather than straight to production (`master`)

**Pull request merged**
