### PR TITLE
Add holders and price infos

### LINKED ISSUE #70: Add more info to dashboard
Some issue cannot be gotten from the graph https://github.com/humanprotocol/escrow-dashboard/issues/62 and https://github.com/humanprotocol/escrow-dashboard/issues/61. Please ticket them both up, remembering to add tests.

### PR DESCRIPTION
**Pull request by Charlie85270**
Add holders count from the subgraph and token price from coingecko. Closes #70 and #61 , #62, #50

### CODE REVIEW

**Comment by posix4e** [comment]
1

**Comment by posix4e** [comment]
1) fix build 
1) merge to develop not master

**Review by posix4e — CHANGES_REQUESTED** [review]
1) wrong branch 
2) fix ci

**Review by posix4e — APPROVED** [review]
Good to view @ivhus / @m00n620 . 

@ansaqib please work with @Charlie85270 to give him a date on when we can merge.

**Review by ivhus — APPROVED** [review]

**Review by posix4e — CHANGES_REQUESTED** [review]
Please rebase

**Pull request closed without merging**
