### PR TITLE
feat: added moonbase and moonbeam to chain list

### PR DESCRIPTION
**Pull request by menezesphill**

### CODE REVIEW

**Comment by posix4e** [comment]
@menezesphill i don’t think you integrated with the graph

**Review by posix4e — CHANGES_REQUESTED** [review]
Needs the graph for info

**Review by Jalal-1 — COMMENTED** [review]
Need to create a subgraph in Graph QL and then add the graphqlClientUrl for moonbeam/moonbase

**Comment by menezesphill** [comment]
@posix4e @Jalal-1 I'm on it 👍

**Review by Jalal-1 — APPROVED** [review]

**Review by posix4e — CHANGES_REQUESTED** [review]
Let’s have someone spin up an official thegraph repo @ivhus @Jalal-1

**Pull request closed without merging**
